name: My python workflow

on:
  push:
    branch:
      -main
      -master
  pull_request:
    branch:
      -main
      -master

jobs:
  job1:
    steps:
      - name: setup
      uses: checkout/@v3