# Generated by Django 4.2.16 on 2024-10-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_remove_cart_cart_product_cartproduct_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
