# Generated by Django 4.2.16 on 2024-10-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartproducts',
            field=models.ManyToManyField(to='shopapp.cartproduct'),
        ),
    ]
