# Generated by Django 4.2.16 on 2024-10-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_order_cartproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is tied to an existing order, try using a different one!'}, max_length=100, unique=True),
        ),
    ]
