# Generated by Django 4.2.16 on 2024-10-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_cartproduct_cart_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
