# Generated by Django 4.2.16 on 2024-10-29 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
