# Generated by Django 4.2.16 on 2024-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_order_delivered_order_delivered_time_order_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='tc_product_images'),
        ),
    ]
