# Generated by Django 4.2.16 on 2024-11-09 01:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_product_raw_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='raw_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='tc_raw_files/'),
        ),
    ]
