# Generated by Django 4.2.16 on 2024-11-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_alter_product_raw_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='raw_file',
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
