# Generated by Django 4.2.16 on 2025-02-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_remove_product_raw_file_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tc_product_images'),
        ),
    ]
